### ISSUE TITLE
Missing rskrza1_min_xip_defconfig

### ISSUE THREAD

**Issue by dylad** [renesas-rz/rza_linux-4.9#1]
I would like to know why there is no rskrza1_min_xip_defconfig file for this kernel ? (3.14 kernel has one).
Is this a normal behaviour or a mistake ?

**Comment by seebe** [comment]
Just forgot to make one. Basically, it's the XIP config, but all the drivers stripped out except serial, I2C and a timer. If you think that is helpful, I can add it.

**Comment by dylad** [comment]
> If you think that is helpful, I can add it.

Yes please, I think it would be great to run a skinny XIP kernel !

**Comment by seebe** [comment]
OK, I'll put something together and post it. If not today, then next week.

**Comment by dylad** [comment]
Many thanks @seebe !

**Comment by seebe** [comment]
Just added it. I admit, I did not do a full analysis , I just removed things that were obvious.
However, my resulting xipImage was only 1.7MB and static RAM usage of the kernel was 312KB. I did not measure the dynamic RAM usage of the drivers and subsystems, but I was able to boot the entire system under 2MB of RAM.

**Comment by dylad** [comment]
> my resulting xipImage was only 1.7MB

> I was able to boot the entire system under 2MB of RAM

Wow, sounds promising ! I'll give it a try on monday. Thanks for your help !
I'm closing this issue.
